\doxysection{googletest-\/catch-\/exceptions-\/test.Catch\+Cxx\+Exceptions\+Test Class Reference}
\hypertarget{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test}{}\label{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test}\index{googletest-\/catch-\/exceptions-\/test.CatchCxxExceptionsTest@{googletest-\/catch-\/exceptions-\/test.CatchCxxExceptionsTest}}


Inheritance diagram for googletest-\/catch-\/exceptions-\/test.Catch\+Cxx\+Exceptions\+Test\+:
% FIG 0


Collaboration diagram for googletest-\/catch-\/exceptions-\/test.Catch\+Cxx\+Exceptions\+Test\+:
% FIG 1
\doxysubsubsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\Hypertarget{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_a770d1b43bf35a0785c5a0587fa968093}\label{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_a770d1b43bf35a0785c5a0587fa968093} 
{\bfseries test\+Catches\+Cxx\+Exceptions\+In\+Fixture\+Constructor} (self)
\item 
\Hypertarget{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_a41e035a4b8263198b3e8a8c597a0552f}\label{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_a41e035a4b8263198b3e8a8c597a0552f} 
{\bfseries test\+Catches\+Cxx\+Exceptions\+In\+Fixture\+Destructor} (self)
\item 
\Hypertarget{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_a2406019fe737e60094300774082667ad}\label{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_a2406019fe737e60094300774082667ad} 
{\bfseries test\+Catches\+Cxx\+Exceptions\+In\+Set\+Up\+Test\+Case} (self)
\item 
\Hypertarget{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_a9955eae0d7f374cacd4d94a87c077e77}\label{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_a9955eae0d7f374cacd4d94a87c077e77} 
{\bfseries test\+Catches\+Cxx\+Exceptions\+In\+Tear\+Down\+Test\+Case} (self)
\item 
\Hypertarget{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_ae97cc7fe22bfb8fe15e1966a8d56d225}\label{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_ae97cc7fe22bfb8fe15e1966a8d56d225} 
{\bfseries test\+Catches\+Cxx\+Exceptions\+In\+Set\+Up} (self)
\item 
\Hypertarget{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_aed4ef281f6c99a7e749ff90e072c6969}\label{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_aed4ef281f6c99a7e749ff90e072c6969} 
{\bfseries test\+Catches\+Cxx\+Exceptions\+In\+Tear\+Down} (self)
\item 
\Hypertarget{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_a7c4e424c079c38b64c8fb849db4949d7}\label{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_a7c4e424c079c38b64c8fb849db4949d7} 
{\bfseries test\+Catches\+Cxx\+Exceptions\+In\+Test\+Body} (self)
\item 
\Hypertarget{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_a2fca0f2016be6890477e8361f6aaabd3}\label{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_a2fca0f2016be6890477e8361f6aaabd3} 
{\bfseries test\+Catches\+Non\+Std\+Cxx\+Exceptions} (self)
\item 
\Hypertarget{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_a779012a964453a445ee8ec2579e2848b}\label{classgoogletest-catch-exceptions-test_1_1_catch_cxx_exceptions_test_a779012a964453a445ee8ec2579e2848b} 
{\bfseries test\+Unhandled\+Cxx\+Exceptions\+Abort\+The\+Program} (self)
\end{DoxyCompactItemize}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Tests C++ exception-catching behavior.

   Tests in this test case verify that:
   * C++ exceptions are caught and logged as C++ (not SEH) exceptions
   * Exception thrown affect the remainder of the test work flow in the
     expected manner.
\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/\+Users/yjack/\+Git\+Hub/\+Sim\+Evo/build/\+\_\+deps/googletest-\/src/googletest/test/googletest-\/catch-\/exceptions-\/test.\+py\end{DoxyCompactItemize}
